### ISSUE TITLE
First

### ISSUE THREAD

**Issue by susanne-loidl** [susanne-loidl/ghedu-github-flow-IT4#1]
Create initial [HTML 5-compatible] (https://www.w3schools.com/html/html5_intro.asp) page called *index.html*. The `body` will stay empty. Add a JavaScript file *index.js* and reference it from *index.html*. For now, *index.js* can also remain empty.

**Comment by Javaw0cky** [comment]
Jetzt hab ich euch schon 1000x erklärt ihr sollt [Bootstrap](http://getbootstrap.com/) verwenden, damit das auch wie eine richtige Website aussieht!

**Comment by susanne-loidl** [comment]
I want to be thaught!!!

**Comment by Javaw0cky** [comment]
taught or thought?

**Comment by susanne-loidl** [comment]
taught
